### ISSUE TITLE
pisound-config fails on non-Unicode locale

### ISSUE THREAD

**Issue by mzero** [BlokasLabs/pisound#3]
If your terminal is in the default C or POSIX locale, then pisound-config fails:

```
[1001] : locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

[1002] : sudo pisound-config
Traceback (most recent call last):
  File "/usr/local/pisound/pisound-config/main.py", line 138, in <module>
    loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 710, in _loop
    self._entering_idle()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 671, in _entering_idle
    callback()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 579, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 839, in draw_screen
    self.write(l)
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 268, in write
    self._term_output_file.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2764' in position 1: ordinal not in range(128)
```

The work around is to set the locale explicitly:

```
[1003] : locale -a
C
C.UTF-8
POSIX
en_US.utf8

[1004] : LANG=C.UTF-8 sudo pisound-config
```

**Comment by gtrainavicius** [comment]
Fixed, run 'Update Pisound' in pisound-config to get the fix.
